server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_labs
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
  rabbitmq:
    addresses: ************************************************************

  mail:
    host: smtp.gmail.com
    port: 587
    username: ********@gmail.com
    password: **** **** **** ****
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

broker:
  queue:
    email:
        name: default.email






